2020-07-01 10:44:04,473 - HistArbEventLogger - ERROR - Can't Fetch Fund Holdings Data for etf: XLK
2020-07-01 10:44:04,473 - HistArbEventLogger - ERROR - Can't Fetch Fund Holdings Data for etf: XLK
2020-07-01 10:44:04,484 - HistArbEventLogger - ERROR - 18.213.229.80:27017: timed out
Traceback (most recent call last):
  File "../CalculateETFArbitrage/LoadEtfHoldings.py", line 79, in getAllETFData
    etfdata = ETF.objects(ETFTicker=etfname, FundHoldingsDate__lte=fundholdingsdate).order_by(
  File "/Users/adityanaik/.local/share/virtualenvs/env-iqJZaY1K/lib/python3.8/site-packages/mongoengine/queryset/base.py", line 287, in first
    result = queryset[0]
  File "/Users/adityanaik/.local/share/virtualenvs/env-iqJZaY1K/lib/python3.8/site-packages/mongoengine/queryset/base.py", line 191, in __getitem__
    queryset._cursor[key],
  File "/Users/adityanaik/.local/share/virtualenvs/env-iqJZaY1K/lib/python3.8/site-packages/pymongo/cursor.py", line 614, in __getitem__
    for doc in clone:
  File "/Users/adityanaik/.local/share/virtualenvs/env-iqJZaY1K/lib/python3.8/site-packages/pymongo/cursor.py", line 1156, in next
    if len(self.__data) or self._refresh():
  File "/Users/adityanaik/.local/share/virtualenvs/env-iqJZaY1K/lib/python3.8/site-packages/pymongo/cursor.py", line 1050, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "/Users/adityanaik/.local/share/virtualenvs/env-iqJZaY1K/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1810, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/Users/adityanaik/.local/share/virtualenvs/env-iqJZaY1K/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1763, in __start_session
    server_session = self._get_server_session()
  File "/Users/adityanaik/.local/share/virtualenvs/env-iqJZaY1K/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1796, in _get_server_session
    return self._topology.get_server_session()
  File "/Users/adityanaik/.local/share/virtualenvs/env-iqJZaY1K/lib/python3.8/site-packages/pymongo/topology.py", line 482, in get_server_session
    self._select_servers_loop(
  File "/Users/adityanaik/.local/share/virtualenvs/env-iqJZaY1K/lib/python3.8/site-packages/pymongo/topology.py", line 208, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: 18.213.229.80:27017: timed out
2020-07-01 10:44:04,484 - HistArbEventLogger - ERROR - 18.213.229.80:27017: timed out
Traceback (most recent call last):
  File "../CalculateETFArbitrage/LoadEtfHoldings.py", line 79, in getAllETFData
    etfdata = ETF.objects(ETFTicker=etfname, FundHoldingsDate__lte=fundholdingsdate).order_by(
  File "/Users/adityanaik/.local/share/virtualenvs/env-iqJZaY1K/lib/python3.8/site-packages/mongoengine/queryset/base.py", line 287, in first
    result = queryset[0]
  File "/Users/adityanaik/.local/share/virtualenvs/env-iqJZaY1K/lib/python3.8/site-packages/mongoengine/queryset/base.py", line 191, in __getitem__
    queryset._cursor[key],
  File "/Users/adityanaik/.local/share/virtualenvs/env-iqJZaY1K/lib/python3.8/site-packages/pymongo/cursor.py", line 614, in __getitem__
    for doc in clone:
  File "/Users/adityanaik/.local/share/virtualenvs/env-iqJZaY1K/lib/python3.8/site-packages/pymongo/cursor.py", line 1156, in next
    if len(self.__data) or self._refresh():
  File "/Users/adityanaik/.local/share/virtualenvs/env-iqJZaY1K/lib/python3.8/site-packages/pymongo/cursor.py", line 1050, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "/Users/adityanaik/.local/share/virtualenvs/env-iqJZaY1K/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1810, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/Users/adityanaik/.local/share/virtualenvs/env-iqJZaY1K/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1763, in __start_session
    server_session = self._get_server_session()
  File "/Users/adityanaik/.local/share/virtualenvs/env-iqJZaY1K/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1796, in _get_server_session
    return self._topology.get_server_session()
  File "/Users/adityanaik/.local/share/virtualenvs/env-iqJZaY1K/lib/python3.8/site-packages/pymongo/topology.py", line 482, in get_server_session
    self._select_servers_loop(
  File "/Users/adityanaik/.local/share/virtualenvs/env-iqJZaY1K/lib/python3.8/site-packages/pymongo/topology.py", line 208, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: 18.213.229.80:27017: timed out
2020-07-01 10:44:32,523 - HistArbEventLogger - ERROR - Can't Fetch Fund Holdings Data for etf: XLK
2020-07-01 10:44:32,524 - HistArbEventLogger - ERROR - Can't Fetch Fund Holdings Data for etf: XLK
2020-07-01 10:44:32,545 - HistArbEventLogger - ERROR - 18.213.229.80:27017: timed out
Traceback (most recent call last):
  File "../CalculateETFArbitrage/LoadEtfHoldings.py", line 79, in getAllETFData
    etfdata = ETF.objects(ETFTicker=etfname, FundHoldingsDate__lte=fundholdingsdate).order_by(
  File "/Users/adityanaik/.local/share/virtualenvs/env-iqJZaY1K/lib/python3.8/site-packages/mongoengine/queryset/base.py", line 287, in first
    result = queryset[0]
  File "/Users/adityanaik/.local/share/virtualenvs/env-iqJZaY1K/lib/python3.8/site-packages/mongoengine/queryset/base.py", line 191, in __getitem__
    queryset._cursor[key],
  File "/Users/adityanaik/.local/share/virtualenvs/env-iqJZaY1K/lib/python3.8/site-packages/pymongo/cursor.py", line 614, in __getitem__
    for doc in clone:
  File "/Users/adityanaik/.local/share/virtualenvs/env-iqJZaY1K/lib/python3.8/site-packages/pymongo/cursor.py", line 1156, in next
    if len(self.__data) or self._refresh():
  File "/Users/adityanaik/.local/share/virtualenvs/env-iqJZaY1K/lib/python3.8/site-packages/pymongo/cursor.py", line 1050, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "/Users/adityanaik/.local/share/virtualenvs/env-iqJZaY1K/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1810, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/Users/adityanaik/.local/share/virtualenvs/env-iqJZaY1K/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1763, in __start_session
    server_session = self._get_server_session()
  File "/Users/adityanaik/.local/share/virtualenvs/env-iqJZaY1K/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1796, in _get_server_session
    return self._topology.get_server_session()
  File "/Users/adityanaik/.local/share/virtualenvs/env-iqJZaY1K/lib/python3.8/site-packages/pymongo/topology.py", line 482, in get_server_session
    self._select_servers_loop(
  File "/Users/adityanaik/.local/share/virtualenvs/env-iqJZaY1K/lib/python3.8/site-packages/pymongo/topology.py", line 208, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: 18.213.229.80:27017: timed out
2020-07-01 10:44:32,545 - HistArbEventLogger - ERROR - 18.213.229.80:27017: timed out
Traceback (most recent call last):
  File "../CalculateETFArbitrage/LoadEtfHoldings.py", line 79, in getAllETFData
    etfdata = ETF.objects(ETFTicker=etfname, FundHoldingsDate__lte=fundholdingsdate).order_by(
  File "/Users/adityanaik/.local/share/virtualenvs/env-iqJZaY1K/lib/python3.8/site-packages/mongoengine/queryset/base.py", line 287, in first
    result = queryset[0]
  File "/Users/adityanaik/.local/share/virtualenvs/env-iqJZaY1K/lib/python3.8/site-packages/mongoengine/queryset/base.py", line 191, in __getitem__
    queryset._cursor[key],
  File "/Users/adityanaik/.local/share/virtualenvs/env-iqJZaY1K/lib/python3.8/site-packages/pymongo/cursor.py", line 614, in __getitem__
    for doc in clone:
  File "/Users/adityanaik/.local/share/virtualenvs/env-iqJZaY1K/lib/python3.8/site-packages/pymongo/cursor.py", line 1156, in next
    if len(self.__data) or self._refresh():
  File "/Users/adityanaik/.local/share/virtualenvs/env-iqJZaY1K/lib/python3.8/site-packages/pymongo/cursor.py", line 1050, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "/Users/adityanaik/.local/share/virtualenvs/env-iqJZaY1K/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1810, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/Users/adityanaik/.local/share/virtualenvs/env-iqJZaY1K/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1763, in __start_session
    server_session = self._get_server_session()
  File "/Users/adityanaik/.local/share/virtualenvs/env-iqJZaY1K/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1796, in _get_server_session
    return self._topology.get_server_session()
  File "/Users/adityanaik/.local/share/virtualenvs/env-iqJZaY1K/lib/python3.8/site-packages/pymongo/topology.py", line 482, in get_server_session
    self._select_servers_loop(
  File "/Users/adityanaik/.local/share/virtualenvs/env-iqJZaY1K/lib/python3.8/site-packages/pymongo/topology.py", line 208, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: 18.213.229.80:27017: timed out
2020-07-01 15:28:59,473 - HistArbEventLogger - ERROR - Can't Fetch Fund Holdings Data for etf: XLK
2020-07-01 15:28:59,474 - HistArbEventLogger - ERROR - Can't Fetch Fund Holdings Data for etf: XLK
2020-07-01 15:28:59,481 - HistArbEventLogger - ERROR - 18.213.229.80:27017: timed out
Traceback (most recent call last):
  File "../CalculateETFArbitrage/LoadEtfHoldings.py", line 79, in getAllETFData
    etfdata = ETF.objects(ETFTicker=etfname, FundHoldingsDate__lte=fundholdingsdate).order_by(
  File "/Users/adityanaik/.local/share/virtualenvs/env-iqJZaY1K/lib/python3.8/site-packages/mongoengine/queryset/manager.py", line 37, in __get__
    queryset = queryset_class(owner, owner._get_collection())
  File "/Users/adityanaik/.local/share/virtualenvs/env-iqJZaY1K/lib/python3.8/site-packages/mongoengine/document.py", line 207, in _get_collection
    db = cls._get_db()
  File "/Users/adityanaik/.local/share/virtualenvs/env-iqJZaY1K/lib/python3.8/site-packages/mongoengine/document.py", line 185, in _get_db
    return get_db(cls._meta.get("db_alias", DEFAULT_CONNECTION_NAME))
  File "/Users/adityanaik/.local/share/virtualenvs/env-iqJZaY1K/lib/python3.8/site-packages/mongoengine/connection.py", line 367, in get_db
    db.authenticate(
  File "/Users/adityanaik/.local/share/virtualenvs/env-iqJZaY1K/lib/python3.8/site-packages/pymongo/database.py", line 1468, in authenticate
    self.client._cache_credentials(
  File "/Users/adityanaik/.local/share/virtualenvs/env-iqJZaY1K/lib/python3.8/site-packages/pymongo/mongo_client.py", line 749, in _cache_credentials
    server = self._get_topology().select_server(
  File "/Users/adityanaik/.local/share/virtualenvs/env-iqJZaY1K/lib/python3.8/site-packages/pymongo/topology.py", line 233, in select_server
    return random.choice(self.select_servers(selector,
  File "/Users/adityanaik/.local/share/virtualenvs/env-iqJZaY1K/lib/python3.8/site-packages/pymongo/topology.py", line 192, in select_servers
    server_descriptions = self._select_servers_loop(
  File "/Users/adityanaik/.local/share/virtualenvs/env-iqJZaY1K/lib/python3.8/site-packages/pymongo/topology.py", line 208, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: 18.213.229.80:27017: timed out
2020-07-01 15:28:59,481 - HistArbEventLogger - ERROR - 18.213.229.80:27017: timed out
Traceback (most recent call last):
  File "../CalculateETFArbitrage/LoadEtfHoldings.py", line 79, in getAllETFData
    etfdata = ETF.objects(ETFTicker=etfname, FundHoldingsDate__lte=fundholdingsdate).order_by(
  File "/Users/adityanaik/.local/share/virtualenvs/env-iqJZaY1K/lib/python3.8/site-packages/mongoengine/queryset/manager.py", line 37, in __get__
    queryset = queryset_class(owner, owner._get_collection())
  File "/Users/adityanaik/.local/share/virtualenvs/env-iqJZaY1K/lib/python3.8/site-packages/mongoengine/document.py", line 207, in _get_collection
    db = cls._get_db()
  File "/Users/adityanaik/.local/share/virtualenvs/env-iqJZaY1K/lib/python3.8/site-packages/mongoengine/document.py", line 185, in _get_db
    return get_db(cls._meta.get("db_alias", DEFAULT_CONNECTION_NAME))
  File "/Users/adityanaik/.local/share/virtualenvs/env-iqJZaY1K/lib/python3.8/site-packages/mongoengine/connection.py", line 367, in get_db
    db.authenticate(
  File "/Users/adityanaik/.local/share/virtualenvs/env-iqJZaY1K/lib/python3.8/site-packages/pymongo/database.py", line 1468, in authenticate
    self.client._cache_credentials(
  File "/Users/adityanaik/.local/share/virtualenvs/env-iqJZaY1K/lib/python3.8/site-packages/pymongo/mongo_client.py", line 749, in _cache_credentials
    server = self._get_topology().select_server(
  File "/Users/adityanaik/.local/share/virtualenvs/env-iqJZaY1K/lib/python3.8/site-packages/pymongo/topology.py", line 233, in select_server
    return random.choice(self.select_servers(selector,
  File "/Users/adityanaik/.local/share/virtualenvs/env-iqJZaY1K/lib/python3.8/site-packages/pymongo/topology.py", line 192, in select_servers
    server_descriptions = self._select_servers_loop(
  File "/Users/adityanaik/.local/share/virtualenvs/env-iqJZaY1K/lib/python3.8/site-packages/pymongo/topology.py", line 208, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: 18.213.229.80:27017: timed out
